### ISSUE TITLE
没有考虑把各种exporter 的添加删除使用counsul管理呢？

### ISSUE THREAD

**Issue by dissipator** [starsliao/ConsulManager#1]
没有考虑把各种exporter 的添加删除使用counsul管理呢？

**Comment by starsliao** [comment]
因为站点接口监控的来源不确定性，所以目前只针对站点监控，做了通过web来对资源增删管理。

对于主机、数据库等场景，因为是使用的云资源，比较好的实践方式是：通过云厂商的接口来获取到主机或者数据库的信息，然后写入到consul service，这样在云上增删了资源，只需要调用接口就可以同步到consul，而不需要人工维护。

当然，如果你需要手动维护，也可以使用本工具的consul管理页面或导入脚本来手动维护其它exporter的资源信息，需要自己定义好各个字段。

**Comment by dissipator** [comment]
ok

**Comment by starsliao** [comment]
@dissipator  目前增加了接入各云厂商的ECS自动同步到consul
