### ISSUE TITLE
可否支持自定义端口的选项？

### ISSUE THREAD

**Issue by Shane-Meng** [starsliao/ConsulManager#12]
非常感谢，你的产品在工作中用到了，非常实用美观。我所负责支持的公司，不支持实用默认端口。比如node-expoter的9100，我发现从阿里云导入后，exporter默认使用的是9100，我试着从实例管理->剪辑->手动改成19100（端口和meta上下两个位置），过一会就又变回9100了。

**Comment by starsliao** [comment]
目前自动同步的主机端口是固定我，我想下怎么优化下这部分，支持手动修改端口不会被同步覆盖。

**Comment by starsliao** [comment]
> 非常感谢，你的产品在工作中用到了，非常实用美观。我所负责支持的公司，不支持实用默认端口。比如node-expoter的9100，我发现从阿里云导入后，exporter默认使用的是9100，我试着从实例管理->剪辑->手动改成19100（端口和meta上下两个位置），过一会就又变回9100了。
0.6.5版本已发布，云主机同步支持自定义IP端口功能，可在【云主机列表】菜单操作。

**Comment by peytonyip** [comment]
你好，新的云MySQL是否也可以增加支持这个功能呢？目前 rds 和 ConsulManager 在不同的云上，有类似的情况，希望可以把阿里云 rds 的地址改为外网的地址和端口

**Comment by starsliao** [comment]
> 你好，新的云 MySQL 是否也可以增加支持这个功能呢？目前 RDS 和 ConsulManager 在不同的云上，有类似的情况，希望可以把阿里云 RDS 的地址改为外网的地址和端口

已经排期在做了。
