### ISSUE TITLE
支持同步阿里云云主机标签

### ISSUE THREAD

**Issue by uglyliu** [starsliao/ConsulManager#16]
请问下大佬，同步阿里云云主机标签这个功能有计划做不，这样的话，设置报警就可以精细化了，研发爸爸们的各类特殊的报警需求搞的头大

**Comment by starsliao** [comment]
同步阿里云ECS支持同步ECS的标签到Consul的meta中，注意标签的key有中文或符号会忽略，因为meta的key不支持。

**Comment by starsliao** [comment]
同步阿里云ECS支持同步ECS的标签到Consul的meta中，注意标签的key有中文或符号会忽略，因为meta的key不支持。
