### ISSUE TITLE
支持同步阿里云云主机时选择内网ip或者外网ip选项

### ISSUE THREAD

**Issue by zhangshenglong521** [starsliao/ConsulManager#18]
支持同步阿里云云主机时选择内网ip或者外网ip选项，我们Prometheus部署自内网机器上。通过信任公司出口ip访问阿里云暴露的node，现在默认同步的是阿里云内网地址，希望可以选择

**Comment by starsliao** [comment]
这样会有个问题，就是所有ecs都需要有外网IP，确认这是你需要的需求么？

**Comment by starsliao** [comment]
0.6.5版本已发布，云主机同步支持自定义IP端口功能，可在【云主机列表】菜单操作。

下个迭代增加同步时候可选择内网或者外网IP，没有外网IP的ECS默认使用内网IP

**Comment by pickleqin** [comment]
既然是多云管理肯定是只有当前部署的云是能内网通，其他云是无法通过内网地址通讯的

**Comment by starsliao** [comment]
> 

consulmanager是不需要与云资源本身通讯的，只是同步信息给consul，之前想法是确保prometheus可以与云资源通讯即可。

目前看是有很多需要使用外网IP通讯的场景。

已经排期增加一个优先获取外网IP的功能。
