### ISSUE TITLE
调用华为云报错

### ISSUE THREAD

**Issue by Mr-xin-Z** [starsliao/ConsulManager#19]
由于没有开通 华为企业项目管理服务 ，造成添加华为云ECS失败。这个能做选择么？ 不开通“ 华为企业项目管理服务” 也能添加ecs

**Comment by starsliao** [comment]
因为分组信息是从企业项目获取的，所以未开通企业项目的会报错，企业账号建议开通，方便管理，

您的需求，我这边近期看下增加使用使用网段来分组，应该可以解决。

您也可以加群沟通下。
