### ISSUE TITLE
采用最新的镜像时，漏洞通知出现bug

### ISSUE THREAD

**Issue by NobitaPassword** [starsliao/ConsulManager#22]
麻烦大佬确认下，这块是不是有问题
我使用最新的镜像，配置漏洞通知时，只配置钉钉通知，测试时，发现报500错误，docker 日志如下：
![image](https://user-images.githubusercontent.com/95348307/176106048-e905f2e7-136a-4f73-929e-4b5d4b02c31f.png)
然后我把微信通知也同时打开，但是HOOK 地址为空，发现可以正常采集和发送通知

**Comment by starsliao** [comment]
确实是有个bug，我修复下这部分代码。
