### ISSUE TITLE
scanning-ittc-ku-edu服务

### ISSUE THREAD

**Issue by 101536363** [starsliao/ConsulManager#23]
麻烦咨询下 我在搭建后接入到consul不就  出现了scanning-ittc-ku-edu的一个节点 状态不可用 这个服务器是咱们的吗？

**Comment by starsliao** [comment]
不是呀，  consulmanager除了配置的连接云厂商同步，默认不会对外发起请求的。
你看看这个是不是你安装consul的主机？

没有没详细的错误描述或者截图？
