### ISSUE TITLE
关于站点1h可用性告警，恢复时间获取到的数据类型为null，有大佬遇到同样的问题吗。其他告警项则正常

### ISSUE THREAD

**Issue by cdy668** [starsliao/ConsulManager#32]
告警规则：
  - alert: 站点1h可用性低于80%
    expr: sum_over_time(probe_success[1h])/count_over_time(probe_success[1h]) * 100 < 80
    for: 3m
    labels:
      alertype: domain
      severity: warning
    annotations:
      description: "{{ $labels.env }}_{{ $labels.name }}({{ $labels.project }})：站点1h可用性：{{ $value | humanize }}%\n
> {{ $labels.instance }}"

为null时，消息推送后拿到的时间为:0001-01-01 08:00:00

告警模板如下
恢复时间: {{ ($alert.EndsAt.Add 28800e9).Format "2006-01-02 15:04:05" }}

**Comment by starsliao** [comment]
我记得prometheus的恢复时间需要自己计算，prometheus的恢复时间一直是显示的0001-01-01 08:00:00

**Comment by starsliao** [comment]
我看alertmanager输出的原始json ，很多的恢复告警的"endsAt": "0001-01-01T00:00:00Z",
