### ISSUE TITLE
ConsulManager 同步多个腾讯云账号异常

### ISSUE THREAD

**Issue by Mr-xin-Z** [starsliao/ConsulManager#35]
反馈BUG, 配个多个腾讯云账号，同步ECS资产后，只有最后一个同步的账号才会显示ECS主机，其他腾讯账号ECS资产里面空了

**Comment by starsliao** [comment]
能查看下日志看下具体有没有报错么？
我这边阿里云、华为云多账号都是正常的，因为腾讯云只有一个账号没测试，不过每个同步都是一个独立的定时任务。你可以点下同步看下，另外注意下区域有没有正确，目前不支持轻量服务器的同步。
