### ISSUE TITLE
ConsulManager 云资源监控-自检主机管理

### ISSUE THREAD

**Issue by Mr-xin-Z** [starsliao/ConsulManager#36]
版本v0.8.1
自建主机管理-导入300台主机，显示导入成功，实际显示15台，
日志:
![image](https://user-images.githubusercontent.com/22376346/183638489-f6ba5556-0950-4087-bfef-9c1aff4fa679.png)

flask 日志显示：
![image](https://user-images.githubusercontent.com/22376346/183638866-cf7ae836-b5f9-496c-b09b-fba14da7ea2f.png)

nginx：日志显示
![image](https://user-images.githubusercontent.com/22376346/183639423-7973d465-9204-4bec-8653-c37e8d8b3a8e.png)

没看到报错信息，但是前端页面仅显示15台

编辑后 xls文件大小
![image](https://user-images.githubusercontent.com/22376346/183639709-7cfbfb02-da30-45c7-95c6-690a6174fa74.png)

**Comment by starsliao** [comment]
前5个字段有没有重复的？ 重复的会覆盖。

**Comment by starsliao** [comment]
还有问题可以加我微信：starsliao  进群沟通。
