### ISSUE TITLE
启动flask-consul失败

### ISSUE THREAD

**Issue by liuwenzhi0318** [starsliao/ConsulManager#38]
![image](https://user-images.githubusercontent.com/37536326/194743858-7799f187-fd7d-4388-a7a1-d847cf9fe856.png)
docker 一直反复重启

![image](https://user-images.githubusercontent.com/37536326/194743875-fe495720-34da-45a9-bf97-bab236ae3754.png)

**Comment by starsliao** [comment]
![图片](https://user-images.githubusercontent.com/3349611/195223236-3a916eb1-cab6-44c3-a501-44eaec9a1626.png)

检查下consul的 登录token是否正确以及权限，还有可能是从数量的版本太低了。

**Comment by danhuazhou** [comment]
我也遇到了相同问题，我这边排查原因是因为电脑没有uuidgen命令，安装脚本是需要uuidgen命令生成uuid做token的。`sudo apt install uuid-runtime`安装后有了uuidgen命令，再docker-compose安装项目就可以成功启动了。
