### ISSUE TITLE
mysql多export的docker容器一直报错 

### ISSUE THREAD

**Issue by Phoebus888** [starsliao/ConsulManager#40]
![image](https://user-images.githubusercontent.com/45359605/199644159-3bdc3205-b785-4e6c-9547-a4f21fa019a8.png)

```
metrics获取不到数据
```
![image](https://user-images.githubusercontent.com/45359605/199644248-049dcb29-38ac-4059-b19c-a1536ec10e2b.png)

**Comment by starsliao** [comment]
是使用的 静态配置的方式么？

静态配置的job配置少了一条配置项：metrics_path: /probe
加上就行了。 
参考：
https://github.com/starsliao/multi_mysqld_exporter#%E5%8D%95%E7%8B%AC%E4%BD%BF%E7%94%A8mysqld_exporter%E7%9A%84prometheus%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E

已经修正了。
