### ISSUE TITLE
grafana 8919中使用instance似乎不太合理

### ISSUE THREAD

**Issue by warsk29** [starsliao/ConsulManager#41]
grafana 8919中存储类监控（网络等其它监控也有类似问题）使用instance作为条件获取数据，如果几台服务器在内网没有公网地址，通过同一外网转发http请求获取metrics，那么使用instance去获取metrics会导致很多条不相关的记录，因为这几台内网服务器的instance的ip都是一样的，虽然你在查询条件里写了"$instance:.+"，但是似乎端口没有带入进去匹配，因为你的查询条件IP下拉选项过滤了端口？建议使用name来获取或者添加新的条件，或者修复下查询条件IP的内容，使其不过滤端口？

**Comment by starsliao** [comment]
你好，确实有遇到过这样的问题，主要是8919昨晚consulmanager专用的看板，是使用的自动发现的主机的内网IP。

你可以使用下16098这个看板，这个通用的看板，是使用的完整的IP 端口的模式。

**Comment by warsk29** [comment]
> 你好，确实有遇到过这样的问题，主要是8919作为consulmanager专用的看板，是使用的自动发现的主机的内网IP。
> 
> 你可以使用下16098这个看板，这个通用的看板，是使用的完整的IP 端口的模式。

好的
