### ISSUE TITLE
同步jumpserver失败

### ISSUE THREAD

**Issue by chenbucheni** [starsliao/ConsulManager#47]
jumpserver版本1.5.5-101
![a61g3auxl0](https://user-images.githubusercontent.com/108444402/210496029-87b3f0e8-6716-4721-b9bd-a4757ec0bec6.jpg)
调用jumpserver接口发现没有nodes_display字段，只有nodes字段，改为nodes后正常同步

**Comment by starsliao** [comment]
应该是低版本的jumpserver使用的nodes字段，我修改下，做个兼容。
