### ISSUE TITLE
使用multi_mysqld_exporter监控数据库实例出现以下告警信息

### ISSUE THREAD

**Issue by cdy668** [starsliao/ConsulManager#50]
数据库的告警规则中并没有涉及到和站点有关的告警配置。告警规则是引用ConsulManager中的msql数据库的告警规则。为自建的mysql实例

监控告警信息

告警名称：站点可用性
告警级别：critical
故障时间：2023-02-02 17:35:22
实例地址：172.x.x.x:33801
主机名称：xx数据库

**_xx数据库()：站点无法访问
172.x.x.x:33801**

**Comment by starsliao** [comment]
`probe_success{} == 0` 应该是这个指标告警的
修改下：
`probe_success{job="blackbox_exporter"} == 0`
指定job的 probe_success指标才告警。
