### ISSUE TITLE
能否默认用户名，自定义 tags？

### ISSUE THREAD

**Issue by baozhilv** [starsliao/ConsulManager#51]
刚接触这个项目，想问下：

1. 能否更改默认认证用户，不使用 admin？
2. web ui 默认的一些 targe 能否进行自定义，或是批量导入的时候，能否再额外新增 tags？

**Comment by starsliao** [comment]
> 刚接触这个项目，想问下：
> 
>     1. 能否更改默认认证用户，不使用 admin？

目前支持ldap接入，可以使用ldap的账号密码，默认用户名不支持修改，需要自行修改代码。


>     2. web ui 默认的一些 targe 能否进行自定义，或是批量导入的时候，能否再额外新增 tags？

可以在web界面的consul 管理中给单个服务增加tags或者mate。
web界面上的批量导入目前不支持，需要自己修改导入脚本。
