### ISSUE TITLE
无法删除健康检查

### ISSUE THREAD

**Issue by liwanli100** [starsliao/ConsulManager#55]
因为ConsulManager 部署在自建主机上，没法对云平台的 RDS 进行健康检查。 
dial tcp 172.18.196.63:3306: connect: no route to host.  
想要删除健康检查，但是删除后一会又会恢复。  删除实例也是一样
![image](https://user-images.githubusercontent.com/38232900/220550610-2e23c884-2e6b-4d30-91c6-fd1dee034ae3.png)

**Comment by starsliao** [comment]
同步的云资源数据会自动加上健康检查的，目前无法关闭，。只是consul提示连接不上mysql，不过不影响使用。
如果数量不多可以尝试在`Consul 管理/实例管理`中，编辑对应的实例，点击删除健康检查即可。
![图片](https://user-images.githubusercontent.com/3349611/221739745-50473eb8-832c-4421-a543-5184c1e0eeee.png)
