### ISSUE TITLE
云主机定义相同主机名称无法同步到jumpserver

### ISSUE THREAD

**Issue by chenbucheni** [starsliao/ConsulManager#56]
云主机的主机名称相同了好像无法全部同步到jumpserver，能否做个兼容，名称相同的情况下，自动加个123
![image](https://user-images.githubusercontent.com/108444402/222029944-20b86901-e97c-429d-a4f0-cc3d2a3bbc10.png)

**Comment by starsliao** [comment]
jumpserver本身不支持创建同名称的主机，所以会报错，目前是使用的同步的方式，保持jumpserver的主机名称和云主机名称一致，后续考虑添加后缀方式来解决这个问题。
