### ISSUE TITLE
阿里云Redis7.0版本接口信息无PrivateIp字段

### ISSUE THREAD

**Issue by uglyliu** [starsliao/ConsulManager#59]
大佬好，昨天我们在阿里云买了一台redis7.0版本的redis，发现无法同步，然后看了下，redis7.0版本，接口信息就没有PrivateIp字段

![image](https://user-images.githubusercontent.com/22983421/227073013-c714153d-9613-46a1-a4cf-be3a9a3e705a.png)

![50d8OGwJLk](https://user-images.githubusercontent.com/22983421/227073024-95215152-7686-4f63-a002-782cff27eb08.jpg)

**Comment by starsliao** [comment]
新版本有对取不到IP的实例做处理。
![图片](https://user-images.githubusercontent.com/3349611/227074232-4d8afa4e-aecc-4f59-8f71-4c6c1608195a.png)

另外，连接是用的domain字段。
