### ISSUE TITLE
腾讯云同步过来的都是内网ip

### ISSUE THREAD

**Issue by wxhhs** [starsliao/ConsulManager#63]
腾讯云同步过来的都是内网ip 而不是公网ip导致无法检测

**Comment by starsliao** [comment]
目前只有阿里云的提供了选项可以自动采集外网IP,其它云的目前只能采集内网IP,我会再近期加上其它2个云采集外网IP的功能.
临时的话你可以使用云主机管理,自定义实例指定外网IP.
