### ISSUE TITLE
自建主机-redis-mysql管理返回500返回码

### ISSUE THREAD

**Issue by sivanXu001** [starsliao/ConsulManager#65]
![image](https://user-images.githubusercontent.com/73472063/231728498-c1944c02-ba6c-419c-94e2-fe185619280f.png)
![image](https://user-images.githubusercontent.com/73472063/231728602-d6541f93-27ed-43a5-8e8a-9d2c510f2dbb.png)

请教各位大佬有没有遇到过同样的问题，同时配置blackbox和自建主机管理就会在自建主机管理、自建mysql管理、自建redis管理等页面报500返回码。

**Comment by sivanXu001** [comment]
添加自建主机后，站点管理页面则返回500返回码。

**Comment by starsliao** [comment]
麻烦更新consulmanager版本后重试,优化了这部分展示的问题.
