### ISSUE TITLE
你好，Redis启动不起来，能帮忙看看是不是我的配置文件错误了

### ISSUE THREAD

**Issue by billy-shang** [starsliao/ConsulManager#66]
Docker启动一直，Restarting (1) 2 seconds ago 下面是配置文件
version: "3.2"
services:
  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-exporter
    restart: unless-stopped
    command:
      - "-redis.password-file=/redis_passwd.json"
    volumes:
      - /usr/share/zoneinfo/PRC:/etc/localtime
      - /data/consul/docker-compose/redis_passwd.json:/redis_passwd.json
    expose:
      - 9121
    network_mode: "host"

**Comment by starsliao** [comment]
docker-compose logs -f  查看下日志看下具体报错了啥
