### ISSUE TITLE
不支持物理服务器吗？

### ISSUE THREAD

**Issue by ion-lgb** [starsliao/ConsulManager#68]
是不支持物理服务器吗？硬盘，CPU使用率，啥的全显示 no data
<img width="1725" alt="微信截图_20230601174743" src="https://github.com/starsliao/ConsulManager/assets/36908373/3b9d7762-94d8-4e4a-8aab-5be5a9baa570">

**Comment by ion-lgb** [comment]
。。。是我安装错版本了

**Comment by starsliao** [comment]
好的, 有问题也可以加consulmanager交流群.
