### ISSUE TITLE
能不能添加复制按钮

### ISSUE THREAD

**Issue by Romic77** [starsliao/ConsulManager#69]
![image](https://github.com/starsliao/ConsulManager/assets/14304457/87c49bfe-b2ec-4fc0-aa74-41562894dc64)
能不能添加复制按钮，复制选中的行

**Comment by starsliao** [comment]
需求记录,
node-exporter 主机监控新增建议在 `云资源管理/ECS管理/自建主机管理` 里面维护, 新增之后,使用`确认并新增`按钮可以继续添加 并且保留之前填写过的字段,或者选择好菜单后在按新增 会自动填写菜单的内容,以及可以使用导入功能.
