### ISSUE TITLE
【功能】增加同步OpenStack云的ECS列表

### ISSUE THREAD

**Issue by j4ckzh0u** [starsliao/ConsulManager#7]
RT

**Comment by Mr-xin-Z** [comment]
+ 1 这样 IDC 资产也能纳入。但是Openstack 各个版本不一样，造成 开发成本很高

**Comment by starsliao** [comment]
主要是考虑到目前prometheus自身支持 aws，openstack的自动发现功能，所以暂时就没有做这块的自动接入，后续我会考虑加上，接入分组采集，才好替代掉prometheus的这部分自动发现。
